### ISSUE TITLE
maintain timestamp

### ISSUE THREAD

**Issue by awolde** [ndbroadbent/icloud_photos_downloader#10]
Great library, just what I needed. But would be nice if you can keep the timestamp of the files being downloaded.

**Comment by mcirri** [comment]
I modified my own copy to achieve that. Since I am using it with Digikam I also modified the saved structure. In my case everything goes into a folder and the files get the time stamp added to the name. In that way one avoids duplications. Digikam then remembers which file it has already added to the library and which not. I am new to GitHub and my mod is just a quick hack, thus I am reluctant to share it here. I might send it to you if you want it.

**Comment by ndbroadbent** [comment]
Hello, yes that would be great. PRs are always welcome!
