### ISSUE TITLE
Download specific album

### ISSUE THREAD

**Issue by gran33** [ndbroadbent/icloud_photos_downloader#106]
First, super thanks for an awesome tool. I'm using it and it's amazing!

I would like to have the option to download a specific album by his name. For example,  I want to download all my favorite photos.

Thanks in advance.
Ran

**Comment by manderso7** [comment]
I'd like a feature like this as well. How difficult would it be to implement?
Thank you much!

**Comment by menkej** [comment]
I have added this feature to base.py. Where can I submit it? I'm not used to git that much yet and I do not have the rights to push my feature branch. Attaching to this post is not allowed for the file type.

.

**Comment by menkej** [comment]
I implemented in #134. This issue can be closed @ndbroadbent

**Comment by ndbroadbent** [comment]
Thanks for all your help @menkej! Would you be interested in being added as a maintainer for this project?

**Comment by menkej** [comment]
> Thanks for all your help @menkej! Would you be interested in being added as a maintainer for this project?
Ni Nathan,
usually I find way to less time for coding in my spare time (what is that?!)... but I can surely help from time to time and try to hunt after some tickets...

cheers
Jörg

PS: I hope your startup is going well (and way better than our house building...) !

**Comment by ndbroadbent** [comment]
Sure no pressure at all! I was very grateful for all your comments on the project issues, so I would be very happy to add you as a maintainer so that you can also close any issues or merge PRs, etc. I will do that now, and no pressure at all, but thanks for any help you can provide!

Also thanks, yes things are very busy these days so I don't have a lot of time for other projects! Also sorry to hear you are having some issues with your house, but that sounds like an interesting project!
