### ISSUE TITLE
Encoding of credentials

### ISSUE THREAD

**Issue by Obsouleet** [ndbroadbent/icloud_photos_downloader#12]
I like your tool very much. The only thing that annoys me is the fact that I have to give my icloud credentials in pure readable text. In this unsecure times I'd prefer to give it with the best encryption I can get. 

At least I would love to see Base64 encoding which makes it unreadable for someone that isn't too computer-savvy...

**Comment by ndbroadbent** [comment]
Hi @Obsouleet, unfortunately there's not much we can do, since it's a scheduled task that runs repeatedly. If you encrypted your login credentials, then you'd have to log into your computer and type in the password a few times every day, like the TV show Lost.

Storing unencrypted passwords is quite normal in a server environment. On a production server, you will often have some config files that contain plain passwords and API tokens, and you just hope that no-one will be able to break into the server and read those files.

But I think your base64 idea is ok. I would be happy to accept a PR that adds support for base64 encoded credentials. Maybe something like:

```
$ ./download_photos.py ./Photos \
    --credentials-base64 "==ias7dfasfyn9as8ufnas34898sdhfsjd8dfmusdf" \
    --size=original \
    --recent 500 \
    --auto-delete
```

**Comment by hreese** [comment]
Linux and macOS have commandline interfaces for their keyrings, which are usually unlocked in interactive sessions. Here's what I use on Linux:
```
--password $(secret-tool lookup username foo@example.com)
```
Use `secret-tool store --label='iCloud Yourname' username foo@example.com` to store the password beforehand. Warning: your password will still be visible to local users via the process list. It will however prevent your Apple password from getting into permanent storage via your shell's history.

**Comment by rbmagnus** [comment]
I have to run 2fa each time my server reboots (e.g. after maintenance). As it's setup as cron job, this is not woking without doing this step manually in advance. Am I missing something ..?

**Comment by Thamster** [comment]
This keyring functionality was working perfectly fine, I disagree completely with this plaintext password philosophy, there is no need for this , even on servers, and b64 is just a silly workaround. I don't understand why you removed this functionality in May with the following commit. 04c2bf9245a7a594a03d6ce00c87f4c7b66181b7

**Comment by ndbroadbent** [comment]
Hi, I've re-added support for the system keychain.

The main reason I disabled it is because it's not very useful on a Mac - You have to type your password every time to unlock the keychain, which defeats the purpose of an automated script. But I didn't realize that the keychain is unlocked permanently when you sign in on Linux, so this is still useful in that case.

Thanks for the feedback!
