### ISSUE TITLE
HELP! HOW TO FIX THIS ERROR: Got unexpected extra argument

### ISSUE THREAD

**Issue by loui328** [ndbroadbent/icloud_photos_downloader#144]
HELP! HOW TO FIX
Error: Got unexpected extra argument (<download_directory>)
![icloudpd](https://user-images.githubusercontent.com/43541631/65684298-e2b67980-e091-11e9-813b-995ace26b15b.JPG)

**Comment by phayes** [comment]
I also got this error

**Comment by phayes** [comment]
You want to pass your local directory in with the `-d` option, the documentation in the README is out of date.

**Comment by phayes** [comment]
For example:

`icloudpd -d ./Photos --username my-user@gmail,com --password abc123`

**Comment by metahnetoutage** [comment]
Guys, the documentation is out of date, the example above is not fully correct either.
Here is a correct example which works 98% of time, if not do let me know.
icloudpd -d /pathToDesiredDirectory/DesiredDirectoryName -u yourmail@example.com

Press Enter.

You will be prompted to enter your iCloud password and enter it precisely.
You will then be taken through two factor authentication.

Then this software will download your stuff.
I know because I used a Linux machine, namely Ubuntu and it worked. The same exact instruction work on Mac once you installed python3.7 and pip inside python3.7 and did pip upgrade and installed all necessary dependencies. Let me know if this was helpful.

**Comment by gwu888** [comment]
@metahnetoutage - good job and thank you!  I found this script is very useful and your clarification here helped me to achieve a big step. Just let you know that, I am now to this script and looking for **more functionalities**, such as: 
1) list all of the directory names on the icloud;
2) download from the "Shared Albums";
3) understand the actually meaning of --recent 500 \ (my test didn't download the recent ones);
4) understand the actually meaning of --auto-delete \ (my test didn't delete files on icloud) -- actually I don't want to delete files on icloud with this scripts, just sync a given directory on icloud would be greatly helpful.
...etc..., any those info you know would be greatly appreciated. many thanks!  btw, I am willing to work with your guys to maintain and further develop this wonderful scripts!! many thanks to @ndbroadbent as well!
