### ISSUE TITLE
Get rid of "Your Apple-ID has been used..." Mail notifications?

### ISSUE THREAD

**Issue by Garfonso** [ndbroadbent/icloud_photos_downloader#49]
Hi,

is there a way to get rid of these E-Mail notifications? It seems that Apple does send them like every 5-10 days or so. Two factor is disabled. I do not know a lot about iCloud, just set this up to backup photos for my mother.
The notifications talk about "Webbrowser". Does Apple send these notifications always, even for people using a regular browser to access their iCloud stuff? Or is there maybe a cookie (or something) the app could save (and obviously set during http requests) to make apple think it knows the browser and all is fine?
Do you have any insights into this?

**Comment by ndbroadbent** [comment]
Sorry, I don't know if there's any way to disable those email notifications, but I set up a filter in Gmail:

<img width="587" alt="screen shot 2018-03-19 at 2 32 52 am" src="https://user-images.githubusercontent.com/139536/37570099-d95ca236-2b1d-11e8-8ea3-a85743114c59.png">

I included "Operating System: Linux" in the rule so that I would still get alerts for Mac and Windows.
