### ISSUE TITLE
Skipped videos result in "Could not process" message

### ISSUE THREAD

**Issue by ezheidtmann** [ndbroadbent/icloud_photos_downloader#72]
I think a `continue` should be a a `break`.  Will patch if I remember.

**Comment by j4zzcat** [comment]
I'm also getting 'Could not process blahblah.mp4! Maybe try again later.' for every mp4 file I have.
Photos are downloading fine, though.

**Comment by ezheidtmann** [comment]
You need to supply the option to request videos be downloaded. Proper fix
is to avoid such a worrisome message when videos are deliberately skipped.

**Comment by Max-Pol** [comment]
I also found this quite confusing the first time I ran the downloader. In my opinion, it would make much more sense to download the video by default, and add a "--skip-video" flag for those who want to skip the videos.

And by the way, @ndbroadbent thanks a lot for sharing this tool, it's very useful and works like a charm!

**Comment by ndbroadbent** [comment]
Thanks @ezheidtmann, you're right, that should have been a `break`. Otherwise it just continues until reaching the max retries. Have pushed the fix

@Max-Pol Thanks for the feedback! You're right, I think a `--skip-videos` flag makes way more sense than `--download-videos`. I was thinking that a lot of these 4K and slow motion videos can be pretty huge, and I just wanted a copy of my photos. But yeah I think it makes sense to download videos by default. Have pushed the change: https://github.com/ndbroadbent/icloud_photos_downloader/commit/9cb9fdd0db7866f625544f1a7dbb38d3a9804934

Thanks everyone!
