### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by monoprix** [ndbroadbent/icloud_photos_downloader#75]
Hi all,

I'm sorry in advance if this is a very basic question. I don't have the skills to be able to go through the code and acquire the answer for myself.

I was about to start downloading my pictures when the 2FA code request on my iDevice indicated that I was requesting access in London, a few hours flight away from my current location. Then it hit me:
- how are requests to log into my icloud account are handled?
- how are photos transported over the wire to my computer?

I'd rather like to avoid transmitting my (new) credentials in plaintext or downloading my photos insecurely.

Thanks in advance for any help you guys can provide.

**Comment by ndbroadbent** [comment]
Hello, 

* how are requests to log into my icloud account are handled?

Please see the [Authentication section in the README](https://github.com/ndbroadbent/icloud_photos_downloader#authentication), since this should answer all of your questions. 

On the first request you're prompted for a 2FA code (if your account has 2FA enabled). Then the authorization will be remembered for a certain period of time (not sure how long, this is on Apple's end.)

You can provide your account password in plaintext, or store the password in the [System Keyring](https://github.com/ndbroadbent/icloud_photos_downloader#system-keyring). But if you want to run the script automatically with minimal interaction, then plaintext passwords are fine, and it's really not a huge security problem, as long as your computer has an encrypted hard-drive and requires a password to log in.

* how are photos transported over the wire to my computer?

All photos are securely downloaded via https. The download URLs look like this: `https://cvws.icloud-content.com/D/8a17850f-6c84-4b97.....`

**Comment by ndbroadbent** [comment]
Also note that your credentials are securely sent to the Apple servers over a TLS connection (a POST request to https://icloud.com/....)
